symlink:
  - .github/workflows/cli.yml: actions/cli.yml

pre-run:
  - script: |
      if(fs.existsSync('README.md')) fs.renameSync('README.md','_README.md.backup')
      process.env.NEAT_ASK_NPM_NAME = process.cwd().match(/\/([^/]*)$/)[1]

ask:
  - id: cli-type
    description: What type of cli do you want? Single is like 'ls' and 'curl'. Multi is like 'git' or 'homebrew'.
    default: [single, multi]
  - id: npm-name
    description: What is the name of your NPM package? ('name' format or '@scope/name' format)

pre-download:
  - npx oclif $NEAT_ASK_CLI_TYPE --options=yarn,typescript,eslint,mocha --defaults
  - script: if(fs.existsSync('_README.md.backup')) fs.renameSync('_README.md.backup','README.md')

inject:
  - id: cli-contribute
    file: inject/contribute.md
    target: [README.md, docs/CONTRIBUTE.md]
    after: <!-- project-contributing -->
  - id: project-installation
    file: inject/installation.md
    target: README.md

post-run:
  - script: |
      // Change package.json with correct npm package
      const pkgName = process.env.NEAT_ASK_NPM_NAME
      if (pkgName && fs.existsSync('package.json')) {
        const pkgFile = JSON.parse(fs.readFileSync('package.json'))
        pkgFile.name = pkgName
        fs.writeFileSync('package.json', JSON.stringify(pkgFile, null, 2))
      }

ignore: [README.md, actions, inject]
