symlink:
  - .github/workflows/cli.yml: actions/cli.yml

pre-run:
  - node .neat/script.js pre-run

ask:
  - id: cli-type
    description: What type of cli do you want? Single is like 'ls' and 'curl'. Multi is like 'git' or 'homebrew'.
    default: [single, multi]
  - id: npm-name
    description: What is the name of your NPM package? ('name' format or '@scope/name' format)
    default: ${node -e 'console.log(process.cwd().match(/\/([^/]*)$/)[1])'}

pre-download:
  - npx oclif $NEAT_ASK_CLI_TYPE --options=yarn,typescript,eslint,mocha --defaults
  - node .neat/script.js pre-download

inject:
  - id: project-contributing
    file: inject/contribute.md
    target: [README.md, docs/CONTRIBUTE.md]
  - id: project-installation
    file: inject/installation.md
    target: README.md

ignore: [README.md, actions, inject]
