symlink:
  - .github/workflows/cli.yml: actions/cli.yml

pre-run:
  - node -e "fs=require('fs');if(fs.existsSync('README.md'))fs.renameSync('README.md','_README.md.backup')"
  - script: |
    const current_folder = process.cwd().match(/\/([^/]*)$/)[1]
    process.env['NEAT_ASK_NPM_NAME'] = current_folder

ask:
  - id: cli-type
    description: What type of cli do you want? Single is like 'ls' and 'curl'. Multi is like 'git' or 'homebrew'.
    default: [single, multi]
  - id: npm-name
    description: What is the name of your NPM package? ('name' format or '@scope/name' format)

pre-download:
  - npx oclif $NEAT_ASK_CLI_TYPE --options=yarn,typescript,eslint,mocha --defaults
  - node -e "fs=require('fs');if(fs.existsSync('_README.md.backup'))fs.renameSync('_README.md.backup','README.md')"

inject:
  - id: cli-contribute
    file: inject/contribute.md
    target: [README.md, docs/CONTRIBUTE.md]
    after: <!-- project-contributing -->
  - id: project-installation
    file: inject/installation.md
    target: README.md

post-run:
  - node .neat/script.js

ignore: [README.md, actions, inject]
