name: "Build & Publish CLI"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}

      - name: Setup NodeJS environment
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Generate code coverage stats
        run: ./node_modules/.bin/nyc report --extension ts --reporter text-lcov > coverage.lcov

      - name: Publish code coverage stats
        uses: codecov/codecov-action@v1

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
